### ISSUE TITLE
"params.script" is not configurable

### ISSUE THREAD

**Issue by bezoerb** [ivanslf/node-php-fpm#1]
There seems no way to set the script option. If you would change `params.script` top `options.script` it would be possible to define a router script to handle the requests.

**Comment by ivanfilhoz** [comment]
Just updated `README.md` with the `rewrite` option.

**Comment by ivanfilhoz** [comment]
Closing this issue for now. Thanks!

**Comment by bezoerb** [comment]
Thanks for updating the readme. But this doesn't handle my use case. I need to point every request to a router script (e.g. index.php) so it's necessary to set the `SCRIPT_FILENAME` and the `SCRIPT` independently. I could provide a PR if you like.

**Comment by ivanfilhoz** [comment]
Please feel free to submit a PR.

**Comment by ivanfilhoz** [comment]
PR #3 merged

**Comment by bezoerb** [comment]
\o/ 🎉
