### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by thany** [ivanslf/node-php-fpm#9]
I'm sorry to say, but it just doesn't work. I don't get errors, exceptions, logs, crashes, weird behaviour. I don't get *anything at all*.

I copied your example code and ran it with node. Then I went to localhost:8080 and waited. For an eternity.
Nothing.

Then I dove into your code, and to my surprize, it doesn't seem to be calling out to PHP anywhere, ever. It does seem to connect to some fastcgi thing, but I can't figure out how it could ever do anything.

I'm sure I'm missing something, but I have no way of knowing what exactly.

If there's anything that needs to be done to get this project to work, please add it to the documentation?

**Comment by ivanfilhoz** [comment]
Have you ever configured php with nginx?

If not, it is actually simple. To use this package, you must setup an Unix or TCP socket for `php-fpm` and configurate `node-php-fpm` accordingly.

The simplest approach here is to set `php-fpm` to listen in port 9000. For macOS + homebrew, this is the default setup. For most GNU/Linux distros (like Ubuntu), you must [edit the config files](https://serversforhackers.com/c/php-fpm-configuration-the-listen-directive).

Once things are synced, it works like a charm.

**Comment by thany** [comment]
So I need nginx? I have never even touched it. I just want a simple webserver that I can fire up, which I wanted to use a node package for. If I have to set up nginx, I fail to see the use of node-php-fpm?

I'm on Windows btw, but really I'm trying to make a project portable.

I was expecting to configure the path to the php executable. It needs to know where php is, otherwise how could it ever execute anything on php? I could even use the default install locations by default, and have a setting only to override it.

**Comment by ivanfilhoz** [comment]
You do not need nginx at all.

Actually, I changed the original message and things got a little confusing. See, what I really wanted to explain was that configuring `node-php-fpm` is **similar** to nginx.

I mean in the sense that PHP must be running in FastCGI mode. If your installation misses this file, just download the latest NTS package [here](https://windows.php.net/download/).

If you are on Windows, use a service manager like [NSSM](https://nssm.cc/download) or just launch `php-cgi.exe` directly:

```
C:\path_to_php\php-cgi.exe -c C:\path_to_php\php-apache.ini -b 127.0.0.1:9000
```

Then `node-php-fpm` will work like a charm. Give a try.
